<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite id="0" name="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/MessageContainer.spec.js" errors="0" package="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/MessageContainer.spec.js" hostname="localhost" tests="1" failures="1" time="0.833" timestamp="2022-06-03T10:41:44">
    <properties>
    </properties>
    <testcase classname="MessageContainer" name="Wraps MessageDisplay component" time="0">
      <failure message="Error: Cannot call text on an empty DOMWrapper.
    at Object.get (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:1676:27)
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/MessageContainer.spec.js:17:21)
    at Object.asyncJestTest (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="1" name="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/LoginForm.spec.js" errors="0" package="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/LoginForm.spec.js" hostname="localhost" tests="1" failures="1" time="0.842" timestamp="2022-06-03T10:41:44">
    <properties>
    </properties>
    <testcase classname="LoginForm" name="emits an event with user data payload" time="0">
      <failure message="Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoHaveLength[2m([22m[32mexpected[39m[2m)[22m

[1mMatcher error[22m: [31mreceived[39m value must have a length property whose value must be a number

Received has value: [31mundefined[39m
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/LoginForm.spec.js:14:32)
    at Object.asyncJestTest (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="2" name="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/RandomNumber.spec.js" errors="0" package="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/RandomNumber.spec.js" hostname="localhost" tests="3" failures="3" time="0.862" timestamp="2022-06-03T10:41:44">
    <properties>
    </properties>
    <testcase classname="RandomNumber" name="By default, randomNumber data value should be 0" time="0">
      <failure message="Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoContain[2m([22m[32mexpected[39m[2m) // indexOf[22m

Expected substring: [32m&quot;&lt;span&gt;0&lt;/span&gt;&quot;[39m
Received string:    [31m&quot;&lt;div&gt;&lt;span&gt;100&lt;/span&gt;&lt;button&gt;Generate Random Number&lt;/button&gt;&lt;/div&gt;&quot;[39m
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/RandomNumber.spec.js:7:28)
    at Object.asyncJestTest (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="RandomNumber" name="If button is clicked, randomNumber should be between 1 and 10" time="0">
      <failure message="Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBeLessThanOrEqual[2m([22m[32mexpected[39m[2m)[22m

Expected: &lt;= [32m10[39m
Received:    [31m100[39m
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/RandomNumber.spec.js:15:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="RandomNumber" name="If button is clicked, randomNumber should be between 200 and 300" time="0">
      <failure message="Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBeGreaterThanOrEqual[2m([22m[32mexpected[39m[2m)[22m

Expected: &gt;= [32m200[39m
Received:    [31m100[39m
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/RandomNumber.spec.js:27:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="3" name="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/MessageDisplay.spec.js" errors="0" package="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/MessageDisplay.spec.js" hostname="localhost" tests="2" failures="2" time="0.866" timestamp="2022-06-03T10:41:44">
    <properties>
    </properties>
    <testcase classname="MessageDisplay" name="Calls getMessage once and displays message" time="0">
      <failure message="Error: [2mexpect([22m[31mjest.fn()[39m[2m).[22mtoHaveBeenCalledTimes[2m([22m[32mexpected[39m[2m)[22m

Expected number of calls: [32m1[39m
Received number of calls: [31m0[39m
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/MessageDisplay.spec.js:19:24)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="MessageDisplay" name="Displays an error when getMessage call fails" time="0">
      <failure message="Error: [2mexpect([22m[31mjest.fn()[39m[2m).[22mtoHaveBeenCalledTimes[2m([22m[32mexpected[39m[2m)[22m

Expected number of calls: [32m1[39m
Received number of calls: [31m0[39m
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/MessageDisplay.spec.js:31:24)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="4" name="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/AppHeader.spec.js" errors="0" package="/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/AppHeader.spec.js" hostname="localhost" tests="2" failures="2" time="2.969" timestamp="2022-06-03T10:41:44">
    <properties>
    </properties>
    <testcase classname="AppHeader" name="if user is not logged in, do not show logout button" time="0">
      <failure message="Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m

Expected: [32mfalse[39m
Received: [31mtrue[39m
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/AppHeader.spec.js:7:48)
    at Object.asyncJestTest (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="AppHeader" name="if logged in, show logout button" time="0">
      <failure message="TypeError: Cannot add property loggedIn, object is not extensible
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:236:25
    at Array.forEach (&lt;anonymous&gt;)
    at mergeDeep (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:226:25)
    at VueWrapper.setData (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7922:9)
    at Object.&lt;anonymous&gt; (/Users/nikkyamresh/files/frontendVue/frontend/tests/unit/AppHeader.spec.js:12:19)
    at Object.asyncJestTest (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /Users/nikkyamresh/files/frontendVue/frontend/node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>